copilot-instructions.md.j2: .github/copilot-instructions.md
default/extensions.json.j2: .vscode/extensions.json
default/memory.json.j2: .mcp/memory.json
default/remember.prompt.md.j2: .github/prompts/remember.prompt.md
default/create-specification.prompt.md.j2: .github/prompts/create-specification.prompt.md
default/create-implementation-plan.prompt.md.j2: .github/prompts/create-implementation-plan.prompt.md
default/review-and-refactor.prompt.md.j2: .github/prompts/review-and-refactor.prompt.md
fix-tests.prompt.md.j2: .github/prompts/fix-tests.prompt.md
plan-changes.prompt.md.j2: .github/prompts/plan-changes.prompt.md
java-docs.prompt.md.j2: .github/prompts/java-docs.prompt.md
