# This playbook syncronizes template files that should be applied to a repository.
# It ensures that the templates are rendered and copied to the appropriate locations,
# and maintains a log of the last sync operation.

- name: Template Sync Playbook
  hosts: localhost
  vars:
    repo_path: "{{ repo_path | default(ansible_env.PWD) }}"
    template_flavor: "{{ template_flavor | default('default') }}"
    template_dir: "{{ playbook_dir }}/templates/{{ template_flavor }}"
    sync_log_path: "{{ repo_path }}/.template-sync/sync-report.json"

  tasks:
    - name: Ensure github directory exists
      ansible.builtin.file:
        path: "{{ repo_path }}/.github"
        state: directory
        mode: '0755'

    - name: Check if copilot instructions file exists
      ansible.builtin.stat:
        path: "{{ repo_path }}/.github/copilot-instructions.md"
      register: copilot_instructions

    - name: Copy copilot instructions file if it does not exist
      ansible.builtin.template:
        src: copilot-instructions.md.j2
        dest: "{{ repo_path }}/.github/copilot-instructions.md"
        mode: '0644'
      when: not copilot_instructions.stat.exists

    - name: Check if .vscode/mcp.json file exists
      ansible.builtin.stat:
        path: "{{ repo_path }}/.vscode/mcp.json"
      register: mcp_json

    - name: Copy .vscode/mcp.json file if it does not exist
      ansible.builtin.template:
        src: mcp.json.j2
        dest: "{{ repo_path }}/.vscode/mcp.json"
        mode: '0644'
      when: not mcp_json.stat.exists

    - name: Check if .vscode/workspace-sync.json exists
      ansible.builtin.stat:
        path: "{{ repo_path }}/.vscode/workspace-sync.json"
      register: workspace_sync_json
    - name: Create .vscode/workspace-sync.json if it does not exist
      ansible.builtin.copy:
        content: "{}"
        dest: "{{ repo_path }}/.vscode/workspace-sync.json"
        mode: '0644'
      when: not workspace_sync_json.stat.exists
